name: Process Location Request

on:
  issues:
    types: [opened, edited]

jobs:
  process-location-request:
    if: contains(github.event.issue.labels.*.name, 'location-request')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests geopy phonenumbers

      - name: Process Location Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/process_location.py
